#!/bin/bash

cnt=0
prev_ip4=""
set_forward=false


if $set_forward; then
    ./set_iptables eth0 wwan0
    ./set_forward_hass $bearer_ip4;
fi


restart_wwan0() {
    ip link set wwan0 down
    ip a flush dev wwan0
    ip link set wwan0 up
    ip a add $bearer_ip4 dev wwan0
    ip r add default dev wwan0 metric 20
    
    if $set_forward; then
        if [ "$prev_ip4" != "" ]; then
          iptables -t nat -D POSTROUTING -o eth0 -p tcp --dport 8123 -d 192.168.0.11 -j SNAT --to-source $prev_ip4
        fi
    
        iptables -t nat -A POSTROUTING -o eth0 -p tcp --dport 8123 -d 192.168.0.11 -j SNAT --to-source $bearer_ip4
        prev_ip4=$bearer_ip4;
    fi
    # ((prev_ip4=bearer_ip4))
}

# get_modem_number() {
#     IFS='/ ' read -r _ _ _ mm _ mn mt < <(mmcli -L)
# #   echo 'echo: Modem number is' $mn
#     printf "Modem number is: %s\n" $mn
# }

. ./functions.sh

# iptables -N forward_chain
# iptables -A FORWARD forward_chain
# iptables -N forward_hass_chain

for ((;;))
do

    printf "\ncycle %d\n" $cnt
    ((cnt=cnt+1))

    get_modem_number
    # IFS='/ ' read -r _ _ _ mm _ mn mt < <(mmcli -L)
    # printf "Modem number is: %s\n" $mn

#    out=$(mmcli -L)
#    echo $cnt $out
#    ((cnt=cnt+1))

#    out=$(mmcli -m $mn |grep state)
#    echo $out

    IFS='/|: ' read -r _ _ state  _  < <(mmcli -m $mn |grep state)
    printf "Modem state is: %s\n" $state

    if [ "$state" = "disabled" ]; then
        printf "Disabled, try to enable\n"
        out=$(mmcli -m $mn -e)
        echo $out
    fi

    if [ "$state" = "registered" ]; then
        printf "Registered, try to connect\n"
        out=$(mmcli -m $mn --simple-connect=apn=internet.mts.by)
        echo $out
    fi

    # if [ "$state" = *'connected'* ]; then
    if echo "$state" | grep -q -E "connected"; then
        printf "Connected, recheck wwan\n"

        out=$(mmcli -m $mn |grep Bearer)
        bearer_number=${out##*/}
    #    printf "Bearer string %s\n" 
        printf "Bearer number %s\n" $bearer_number

        bearer_ip4=$(mmcli -m $mn -b $bearer_number |grep "address" |grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        echo "Bearer IPv4:" $bearer_ip4 

        wwan_ip4=$(ip a |grep wwan0 |grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        echo "wwan IPv4:" $wwan_ip4
        # echo ""

        if [ "$bearer_ip4" != "$wwan_ip4" ]; then
            echo "bearer" $bearer_number IP not equal to wwan IP
            echo "Reconfigure wwan"
            # ip link set wwan0 down
            # ip a flush dev wwan0
            # ip link set wwan0 up
            # ip a add $bearer_ip4 dev wwan0
            # ip r add default dev wwan0 metric 20
            restart_wwan0
            # ./set_iptables eth0 wwan0
            # ./set_forward_hass $bearer_ip4
        else
            echo "Bearer & wwan have same ip4:" $bearer_ip4
        fi

        # sleep 2

        # res=$(ping 375333526167.dyndns.mts.by -c 1 |grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        # echo "ping 375333526167.dyndns.mts.by answer:" $res 


        # arrIN=(${res// / })
        # echo "ip1=" ${arrIN[0]} "ip2=" ${arrIN[1]}

        # if [ "$bearer_ip4" != "${arrIN[0]}" ]; then
        #     echo "bearer" $bearer_number IP not equal to DNS IP
        #     restart_wwan0
        #     # ./set_iptables eth0 wwan0
        #     # ./set_forward_hass $bearer_ip4
        # else
        #     echo "Bearer & DNS have same ip4:" $bearer_ip4
        # fi

        # IFS=' ' read -ra ADDR <<< "$res"
        # echo "ADDR" $ADDR
        # echo "ADDR[1]" $(ADDR[0])
        # for i in "${ADDR[@]}"; do
        #   echo "$i"
        # done


        #IFS=' ' read -r ip1 ip2 _  < <($res)
        #echo "ping answer ip:" $ip1 $ip2
        
        # IFS=' ' read -r a1 a2 a3 a4 a5 ip1 ip2 _  < <(ping 375333526167.dyndns.mts.by -c 1)
        # echo "ping answer ip:" $a1 $a2 $a3 $a4 $a5 $ip1 $ip2
    else
        printf "Not connected\n"
    fi


   sleep 4 

done
