#!/bin/bash
#run with sudo
printf "run with args %s %s\n" $1 $2 
sysctl net.ipv4.ip_forward=1
#iptables -F forward_chain
iptables -A FORWARD -i $1 -o $2 -j ACCEPT
iptables -A FORWARD -o $1 -i $2 -j ACCEPT
iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
# iptables -F forward_chain
# iptables -A forward_chain FORWARD -i $1 -o $2 -j ACCEPT
# iptables -A forward_chain FORWARD -o $1 -i $2 -j ACCEPT
# iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
